name: KRX Prediction CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Start services using Docker Compose
        run: docker compose up -d --remove-orphans
