name: KRX Prediction CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Stop and remove existing Docker Compose containers
        run: |
          sudo docker compose stop
          sudo docker compose down --volumes --remove-orphans

      - name: Build Docker images
        run: sudo docker compose build

      - name: Start services using Docker Compose
        run: sudo docker compose up -d --remove-orphans
