name: KRX Prediction CI

on:
  push:
    branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .env FILE
        run: |
          echo "$ENV_FILE" >> .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push all services defined in docker-compose.yml
        run: |
          docker compose build
          docker compose push

      - name: Post build
        run: echo "docker compose success"