name: KRX Prediction CI

on:
  push:
    branches: ["main"]

jobs:
    build:
      runs-on: self-hosted
      steps:
        - name: Set up .env FILE
          run: |
            echo "$ENV_FILE" >> .env
          env:
            ENV_FILE: ${{ secrets.ENV_FILE }}

        - name: Docker Compose
          uses: actions/checkout@v3
          run: docker compose up -d